
test_name: "PP_speeds"

architecture: "PP"
pp_speed_mode: "raceline"
raceline: True

n_scans: 2
train_mode: "Std"
test_mode: "Std"

n: 1
set_n: 1

random_seed: 10000

n_train_steps: 100000
n_test_laps: 2
# n_test_laps: 50
noise_std: 0.0

map_name: "f1_esp"
reward: "PP"

runs:
  - max_speed: 4
  - max_speed: 5
  - max_speed: 6
  - max_speed: 7
  - max_speed: 8






