
planner: "Agent"

test_name: "Racing_MapsPPPS"

racing_mode: "Fast"
n_scans: 2
train_mode: "Std"
test_mode: "Std"

n: 5
set_n: 1

random_seed: 10000

n_train_steps: 100000
# n_test_laps: 20
n_test_laps: 50

max_speed: 8
# max_speed: 5

runs:
  - map_name: "f1_esp"
    reward: "PPPS"
  - map_name: "f1_mco"
    reward: "PPPS"
  - map_name: "f1_aut"
    reward: "PPPS"
  - map_name: "f1_gbr"
    reward: "PPPS"







