
test_name: "TAL_maps8"

architecture: "fast"
n_scans: 2
train_mode: "Std"
test_mode: "Std"

start_n: 4
n: 5
set_n: 1

random_seed: 10000

n_train_steps: 100000
n_test_laps: 20
# n_test_laps: 50

max_speed: 8
# max_speed: 6
reward: "TAL"

runs:
  # - map_name: "f1_esp"
  # - map_name: "f1_mco"
  # - map_name: "f1_aut"
  - map_name: "f1_gbr"







